# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-01 11:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pic',
            old_name='pic_name',
            new_name='pic_link',
        ),
        migrations.RemoveField(
            model_name='pic',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='pic',
            name='likes',
        ),
    ]
